# Application settings
app_name: adquotientmedia
app_port: 8007
health_check_path: "/"
env: development

# Domain configuration
domain: adquotient.media

# Target machine (must match inventory.yml)
target_host: production

# SSL settings
ssl_email: yogendra@vasifytech.com

# Docker registry (GitLab) 
registry: registry.gitlab.com
registry_image: registry.gitlab.com/vasify/vasify-docker-registry
